name: wall2wall-linux
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - rasterio
  - scikit-learn
  - joblib
  - pytest
  - pyyaml
  - python-build
  - setuptools
  - wheel
  - packaging=25.0
  - pip:
      - snakemake==9.27.0
